name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 游릭 Unzip app project if zipped
    - name: Unzip project if present
      run: |
        if [ -f app.zip ]; then
          unzip app.zip -d app_src
          mv app_src/* .
        fi

    # 游릭 Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # 游릭 Grant Gradle permissions
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 游릭 Build APK
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # 游릭 Decode and set up signing key
    - name: Decode signing key
      run: |
        echo "$SIGNING_KEY" | base64 --decode > signing-key.jks

    # 游릭 Sign APK
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    # 游릭 Rename based on branch
    - name: Rename APK
      run: |
        cd app/build/outputs/apk/release
        if [ "${{ github.ref_name }}" = "main" ]; then
          mv app-release.apk release.apk
        else
          mv app-release.apk release-beta.apk
        fi

    # 游릭 Upload artifact
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: app/build/outputs/apk/release/*.apk
