name: Unzip and Organize Project

on:
  push:
    paths:
      - "*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Extract zip
        run: |
          mkdir workspace
          unzip '*.zip' -d workspace
          # move files into correct places if needed
          rsync -a workspace/ Eaglercraft-Mobile/
          rm -rf workspace

      - name: Commit organized files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-unzipped project"
          git push
